name: Automation Test CI (API & Web UI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automation-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Java (sesuai project webautomation)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Grant permission for Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Setup Google Chrome (untuk Selenium UI Test)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # 5. Run Automation Tests (API + UI)
      - name: Run Gradle Test
        run: ./gradlew clean test

      # 6. Upload Test Report
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-test-report
          path: |
            build/reports/tests
            build/reports